Repository huawei-noah/SMARTS, pull requests merged in 2020-11, with the labels that each got.

#101 "stateless" BubbleManager using VehicleIndex diffing
  smarts/core/agent_manager.py
  smarts/core/bubble_manager.py
  smarts/core/scenario.py
  smarts/core/sensors.py
  smarts/core/smarts.py
  smarts/core/sumo_traffic_simulation.py
  smarts/core/tests/helpers/providers.py
  smarts/core/tests/test_bubble_manager.py
  smarts/core/tests/test_controller_lane.py
  smarts/core/traffic_history_provider.py
  smarts/core/trap_manager.py
  smarts/core/vehicle_index.py
Labels: this sprint

#138 Issue 89 - Improve RemoteAgent
  smarts/core/agent_manager.py
  smarts/core/remote_agent.py
Labels: good first issue

#81 Memory growth tests
  .github/workflows/ci-base-tests.yml
  .github/workflows/ci-test-learning.yml
  .github/workflows/ci-test-memory-growth.yml
  Makefile
  smarts/core/agent_manager.py
  smarts/core/controllers/__init__.py
  smarts/core/remote_agent.py
  smarts/core/remote_agent_buffer.py
  smarts/core/sensors.py
  smarts/core/tests/test_smarts_memory_growth.py
Labels: bug

#183 Fix and re-enable RLlib example test
  examples/rllib.py
  tests/test_examples.py
Labels: bug

#202 Perform sensor stepping for all vehicles with sensors
  smarts/core/agent_manager.py
  smarts/core/smarts.py
  smarts/core/vehicle_index.py
Labels: this sprint

#204 Fix shadowing agent causing episode done
  scenarios/straight/agent_prefabs.py
  scenarios/straight/scenario.py
  smarts/core/bubble_manager.py
  smarts/core/smarts.py
Labels: this sprint

#191 Support individual vehicles being done (i.e. for Boids)
  scenarios/straight/agent_prefabs.py
  scenarios/straight/scenario.py
  smarts/core/agent_manager.py
  smarts/core/bubble_manager.py
  smarts/core/coordinates.py
  smarts/core/sensors.py
  smarts/core/smarts.py
  smarts/core/sumo_traffic_simulation.py
  smarts/core/tests/test_bubble_manager.py
Labels: this sprint

#176 Support UTurn task
  smarts/core/mission_planner.py
  smarts/core/scenario.py
  smarts/core/utils/math.py
  smarts/sstudio/types.py
Labels: RFC, this sprint
