Repository huawei-noah/SMARTS, pull requests merged in 2020-12, with the labels that each got.

#232 Add shape to LinkledWaypoints
  smarts/core/waypoints.py
Labels: this sprint

#214 Large vehicle urdf interface
  smarts/core/agent_interface.py
  smarts/core/chassis.py
  smarts/core/controllers/__init__.py
  smarts/core/models/bus.urdf
  smarts/core/models/controller_parameters.yaml
  smarts/core/scenario.py
  smarts/core/smarts.py
  smarts/core/tests/test_trajectory_controller.py
  smarts/core/vehicle.py
Labels: this sprint

#238 Support cut-in task
  smarts/core/controllers/lane_following_controller.py
  smarts/core/mission_planner.py
  smarts/core/sensors.py
  smarts/core/vehicle.py
  smarts/sstudio/types.py
Labels: this sprint

#277 Enhance speed tracking performance
  smarts/core/chassis.py
  smarts/core/controllers/lane_following_controller.py
  smarts/core/models/controller_parameters.yaml
  smarts/core/smarts.py
  smarts/core/tests/maps/turning_radius/mapzshape.net.xml
  smarts/core/tests/test_controller_lane.py
  smarts/core/vehicle.py
Labels: this sprint

#284 247 Authenticate
  cli/zoo.py
  examples/single_agent.py
  smarts/core/agent_manager.py
  smarts/core/remote_agent.py
  smarts/core/remote_agent_buffer.py
  smarts/core/smarts.py
  smarts/env/hiway_env.py
  smarts/zoo/run_agent.py
  smarts/zoo/worker.py
Labels: this sprint

#275 41 Include option for ordered scenarios
  smarts/core/scenario.py
  smarts/env/hiway_env.py
Labels: this sprint

#246 Test trap manager
  smarts/core/smarts.py
  smarts/core/tests/test_trap_manager.py
  smarts/core/trap_manager.py
Labels: this sprint

#237 Mention environment reward in the observations.rst
  docs/sim/observations.rst
  smarts/core/tests/test_smarts_memory_growth.py
Labels: this sprint

#281 Waypoints now take into account heading
  smarts/core/controllers/__init__.py
  smarts/core/mission_planner.py
  smarts/core/sensors.py
  smarts/core/smarts.py
  smarts/core/vehicle_index.py
  smarts/core/waypoints.py
Labels: this sprint

#263 Improvments on cut in and u-turn interaction between agents and social vehicles
  smarts/core/controllers/lane_following_controller.py
  smarts/core/mission_planner.py
  smarts/sstudio/generators.py
  smarts/sstudio/tests/baseline.rou.xml
  smarts/sstudio/types.py
  zoo/policies/open-agent/open_agent/agent.py
Labels: this sprint

#286 Fix wrong param of closest_waypoint
  smarts/core/mission_planner.py
  smarts/core/tests/test_sensors.py
Labels: Urgent

#297 Reduce repeated traci calls by subscribing to all vehicles
  smarts/core/sumo_traffic_simulation.py
Labels: this sprint

#306 Add route waypoints in RoadWaypoints
  smarts/core/mission_planner.py
  smarts/core/sensors.py
  smarts/core/vehicle.py
Labels: this sprint

#338 Fix cut in and change obstacle to ellipse
  examples/ego_open_agent.py
  smarts/core/mission_planner.py
  smarts/core/tests/test_sensors.py
  zoo/policies/open-agent/open_agent/agent.py
  zoo/policies/open-agent/open_agent/config.json
  zoo/policies/open-agent/open_agent/version.py
  zoo/policies/python-bindings-open-agent-solver/python_bindings_open_agent_solver-0.0.4-cp37-cp37m-manylinux2010_x86_64.whl
  zoo/policies/python-bindings-open-agent-solver/python_bindings_open_agent_solver-0.0.5-cp37-cp37m-manylinux2010_x86_64.whl
Labels: bm, this sprint

#345 add aggressiveness to uturn
  smarts/core/mission_planner.py
  smarts/core/tests/test_sensors.py
Labels: this sprint

#329 328 fix `Heading.relative_to()` assert on greater than 3 pi difference
  smarts/core/coordinates.py
  smarts/core/tests/test_coordinates.py
Labels: this sprint

#326 Fix `replace()` use in AgentSpec
  smarts/core/agent.py
Labels: this sprint

#311 129 lane change in intersection
  examples/single_agent.py
  scenarios/intersections/4lane/scenario.py
  smarts/core/controllers/lane_following_controller.py
  smarts/core/mission_planner.py
  smarts/core/scenario.py
  smarts/core/sensors.py
  smarts/core/sumo_road_network.py
  smarts/core/sumo_traffic_simulation.py
  smarts/core/trap_manager.py
  smarts/sstudio/generators.py
  smarts/sstudio/genscenario.py
  smarts/sstudio/types.py
Labels: bm, this sprint
