Repository huawei-noah/SMARTS, pull requests merged in 2021-01, with the labels that each got.

#344 Update evaluation algorithm on diversity
  requirements.txt
  zoo/evaluation/metrics/diversity/diversity_evaluation.py
  zoo/evaluation/metrics/diversity/utils.py
  zoo/evaluation/metrics/kinematics/kinematics_evaluation.py
  zoo/evaluation/metrics/run_evaluation.py
  zoo/evaluation/scenarios/straight_change-lane_1/map.net.xml
  zoo/evaluation/scenarios/straight_change-lane_1/scenario.py
  zoo/evaluation/scenarios/straight_change-lane_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_change-lane_2/map.net.xml
  zoo/evaluation/scenarios/straight_change-lane_2/scenario.py
  zoo/evaluation/scenarios/straight_change-lane_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_straight_1/map.net.xml
  zoo/evaluation/scenarios/straight_straight_1/scenario.py
  zoo/evaluation/scenarios/straight_straight_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_straight_2/map.net.xml
  zoo/evaluation/scenarios/straight_straight_2/scenario.py
  zoo/evaluation/scenarios/straight_straight_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_turn-left_1/map.net.xml
  zoo/evaluation/scenarios/straight_turn-left_1/scenario.py
  zoo/evaluation/scenarios/straight_turn-left_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_turn-left_2/map.net.xml
  zoo/evaluation/scenarios/straight_turn-left_2/scenario.py
  zoo/evaluation/scenarios/straight_turn-left_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_uturn_1/map.net.xml
  zoo/evaluation/scenarios/straight_uturn_1/scenario.py
  zoo/evaluation/scenarios/straight_uturn_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/straight_uturn_2/map.net.xml
  zoo/evaluation/scenarios/straight_uturn_2/scenario.py
  zoo/evaluation/scenarios/straight_uturn_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-left_turn-left_1/map.net.xml
  zoo/evaluation/scenarios/turn-left_turn-left_1/scenario.py
  zoo/evaluation/scenarios/turn-left_turn-left_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-left_turn-left_2/map.net.xml
  zoo/evaluation/scenarios/turn-left_turn-left_2/scenario.py
  zoo/evaluation/scenarios/turn-left_turn-left_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-left_uturn_1/map.net.xml
  zoo/evaluation/scenarios/turn-left_uturn_1/scenario.py
  zoo/evaluation/scenarios/turn-left_uturn_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-left_uturn_2/map.net.xml
  zoo/evaluation/scenarios/turn-left_uturn_2/scenario.py
  zoo/evaluation/scenarios/turn-left_uturn_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-right_turn-left_1/map.net.xml
  zoo/evaluation/scenarios/turn-right_turn-left_1/scenario.py
  zoo/evaluation/scenarios/turn-right_turn-left_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-right_turn-left_2/map.net.xml
  zoo/evaluation/scenarios/turn-right_turn-left_2/scenario.py
  zoo/evaluation/scenarios/turn-right_turn-left_2/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-right_uturn_1/map.net.xml
  zoo/evaluation/scenarios/turn-right_uturn_1/scenario.py
  zoo/evaluation/scenarios/turn-right_uturn_1/traffic/ego.rou.xml
  zoo/evaluation/scenarios/turn-right_uturn_2/map.net.xml
  zoo/evaluation/scenarios/turn-right_uturn_2/scenario.py
  zoo/evaluation/scenarios/turn-right_uturn_2/traffic/ego.rou.xml
Labels: bm

#409 Roll back the changes for cutin
  smarts/core/mission_planner.py
Labels: this sprint

#437 Manual and scheduled triggering of Learning test.
  .github/workflows/ci-base-tests.yml
  .github/workflows/ci-formatting-and-dependencies.yml
  .github/workflows/ci-pull-request.yml
  .github/workflows/ci-test-header.yml
  .github/workflows/ci-test-learning.yml
  .github/workflows/ci-test-memory-growth.yml
Labels: this sprint

#439 Fix history vehicles key error + not recreate SMARTS instance
  examples/history_vehicles_replacement_for_imitation_learning.py
  smarts/core/agent_manager.py
  smarts/core/sensors.py
  smarts/core/smarts.py
  smarts/core/trap_manager.py
Labels: this sprint

#435 Remove all vehicle in SUMO when reset
  smarts/core/sumo_traffic_simulation.py
Labels: this sprint

#445 Fix Unclosed File Descriptors In stdout Suppress
  smarts/core/utils/logging.py
Labels: bug, this sprint

#442 Fix the teleport issue for BM
  smarts/core/smarts.py
  smarts/core/sumo_traffic_simulation.py
Labels: bug, this sprint

#446 Fix OpEn for large vehicle
  smarts/core/models/controller_parameters.yaml
  zoo/policies/open-agent/open_agent/agent.py
  zoo/policies/open-agent/open_agent/config.json
  zoo/policies/open-agent/open_agent/version.py
  zoo/policies/python-bindings-open-agent-solver/python_bindings_open_agent_solver-0.0.5-cp37-cp37m-manylinux2010_x86_64.whl
  zoo/policies/python-bindings-open-agent-solver/python_bindings_open_agent_solver-0.0.6-cp37-cp37m-manylinux2010_x86_64.whl
Labels: bug, this sprint

#441 Option for resetting a scenario without restart or reload SUMO
  smarts/core/sumo_traffic_simulation.py
Labels: this sprint

#420 Upgrade to ray 1 0 1 post1 With Fix
  examples/rllib.py
  examples/rllib_agent.py
  requirements.txt
  setup.py
  smarts/env/tests/test_rllib_hiway_env.py
Labels: this sprint

#448 Include ultra directories in header_test.sh
  header_test.sh
Labels: ULTRA

#474 Update Docker Documentation
  README.md
Labels: hotfix
