Repository huawei-noah/SMARTS, pull requests merged in 2022-01, with the labels that each got.

#1178 Move pynput dep out of main dependencies and into extras package
  examples/human_in_the_loop.py
  setup.py
Labels: bug, good first issue

#972 Added a Replay Agent and a Guide on how it can be used.
  .dockerignore
  .gitignore
  CHANGELOG.md
  examples/replay/README.md
  examples/replay/replay_klws_agent.py
  scenarios/intersections/2lane_circle/scenario.py
  scenarios/intersections/4lane_t/scenario.py
  scenarios/loop/scenario.py
  smarts/core/__init__.py
  smarts/core/agent.py
  zoo/policies/__init__.py
  zoo/policies/keep_left_with_speed_agent.py
  zoo/policies/replay_agent.py
Labels: enhancement

#1215 HiWayEnv Gym Environment to support OpenDRIVE Maps
  CHANGELOG.md
  smarts/core/scenario.py
  smarts/env/hiway_env.py
Labels: enhancement, release critical

#1186 Support for OpenDRIVE maps
  CHANGELOG.md
  cli/studio.py
  scenarios/od_4lane/map.xodr
  scenarios/od_4lane/scenario.py
  scenarios/od_merge/map.xodr
  scenarios/od_merge/scenario.py
  scenarios/od_newmarket/map.xodr
  scenarios/od_newmarket/scenario.py
  setup.py
  smarts/core/default_map_builder.py
  smarts/core/lanepoints.py
  smarts/core/opendrive_road_network.py
  smarts/core/road_map.py
  smarts/core/scenario.py
  smarts/core/sumo_lanepoints.py
  smarts/core/sumo_road_network.py
  smarts/core/sumo_traffic_simulation.py
  smarts/core/tests/test_map.py
  smarts/core/utils/geometry.py
  smarts/core/utils/key_wrapper.py
  smarts/core/utils/math.py
  smarts/env/hiway_env.py
  smarts/sstudio/generators.py
  smarts/sstudio/od2mesh.py
  smarts/sstudio/sumo2mesh.py
  smarts/sstudio/tests/test_generate.py
  smarts/sstudio/types.py
Labels: enhancement, refactor, release critical
